spring.application.name=dispute-service


app.datasource.url=jdbc:postgresql://localhost:5432/themisys
app.datasource.username=postgres
app.datasource.password=ofspain86

app.datasource.hikari.maximum-pool-size=100
app.datasource.hikari.connection-timeout=30000
app.datasource.hikari.idle-timeout=300000
app.datasource.hikari.max-lifetime=1800000
app.datasource.hikari.leak-detection-threshold=30000


# Sort operations and tags alphabetically
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.tags-sorter=alpha
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

# or "hashicorp"
vault.provider=aws



# =============================
# Redis Cluster Config
# =============================
# Comma-separated host:port list of cluster nodes
spring.data.redis.nodes=127.0.0.1:6379
# Number of allowed redirects before giving up on cluster commands
spring.data.redis.max-redirects=3

# ACL credentials (if Redis is using ACL authentication)
spring.data.redis.username=default
spring.data.redis.password=

# Command timeout in milliseconds
spring.data.redis.timeout=1000

# =============================
# Lettuce Pool Config
# =============================
spring.data.redis.lettuce.pool.max-idle=50
spring.data.redis.lettuce.pool.min-idle=5
spring.data.redis.lettuce.pool.max-active=50
spring.data.redis.lettuce.pool.max-wait=-1

# How often to run eviction checks (ms)
redis.timeBetweenEvictionRunsMillis=300000

# =============================
# Cluster Topology Refresh
# =============================
# Interval in seconds to refresh Redis cluster topology
spring.redis.lettuce.refresh.period=60

# =============================
# Application-specific
# =============================
# Environment name (used in cache prefix)
application.env=dev
# ACL key prefix for cache keys
acl.redis.key.prefix=nestra

resilience4j.timelimiter.instances.myService.timeout-duration=5s
resilience4j.timelimiter.instances.myService.cancel-running-future=true
